In [20]:
import helpers as hp
import numpy as np
import matplotlib.pyplot as plt
from svm import distance_point_to_hyperplane, compute_margin, plot_data_and_boundary

In [21]:
def cprint(*args):
    print(*args, sep='\n', end='\n\n')

In [22]:
# Parameters
num = 3
training_data = hp.generate_training_data_binary(num)
cprint(training_data)

[[ 3.  2.  1.]
 [ 6.  2.  1.]
 [ 3.  6.  1.]
 [ 4.  4.  1.]
 [ 5.  4.  1.]
 [-1. -2. -1.]
 [-2. -4. -1.]
 [-3. -3. -1.]
 [-4. -2. -1.]
 [-4. -4. -1.]]



In [23]:
# Preprocessing
# Separate into classes
positive_set = []
negative_set = []
for pt in training_data:
    label = pt[-1]
    if label == 1:
        positive_set.append(pt)
    elif label == -1:
        negative_set.append(pt)

positive_set = np.array(positive_set)
negative_set = np.array(negative_set)
cprint(positive_set,negative_set)

[[3. 2. 1.]
 [6. 2. 1.]
 [3. 6. 1.]
 [4. 4. 1.]
 [5. 4. 1.]]
[[-1. -2. -1.]
 [-2. -4. -1.]
 [-3. -3. -1.]
 [-4. -2. -1.]
 [-4. -4. -1.]]



In [24]:
# Enumerate all possible support-vector combinations

# 2 support vectors

two_sv = []
for pos_pt in positive_set:
    for neg_pt in negative_set:
        two_sv.append((pos_pt, neg_pt))
two_sv = np.array(two_sv)

cprint(two_sv[:3])

[[[ 3.  2.  1.]
  [-1. -2. -1.]]

 [[ 3.  2.  1.]
  [-2. -4. -1.]]

 [[ 3.  2.  1.]
  [-3. -3. -1.]]]



In [25]:
# Compute w and b for each pair of support vectors
w_b = []
for pair in two_sv:
    positive_pt = pair[0][:-1]
    negative_pt = pair[1][:-1]
    dist = positive_pt - negative_pt
    dir_w = dist / np.linalg.norm(dist)
    gamma = np.linalg.norm(dist) / 2       # distance/2
    this_w = dir_w * (1 / gamma)           # = dir * (2 / |dist|)
    b = 1 - this_w @ positive_pt

    print(this_w,b)
    w_b.append((this_w,b))
    # cprint(dir_w, gamma, this_w, b)
# cprint(w_b)


[0.25 0.25] -0.24999999999999956
[0.16393443 0.19672131] 0.11475409836065564
[0.19672131 0.16393443] 0.08196721311475408
[0.21538462 0.12307692] 0.10769230769230753
[0.16470588 0.14117647] 0.22352941176470587
[0.21538462 0.12307692] -0.5384615384615388
[0.16 0.12] -0.20000000000000018
[0.16981132 0.09433962] -0.2075471698113207
[0.17241379 0.06896552] -0.1724137931034484
[0.14705882 0.08823529] -0.0588235294117645
[0.1 0.2] -0.5
[0.08 0.16] -0.19999999999999996
[0.1025641  0.15384615] -0.23076923076923062
[0.12389381 0.14159292] -0.22123893805309724
[0.09395973 0.13422819] -0.08724832214765121
[0.16393443 0.19672131] -0.4426229508196722
[0.12 0.16] -0.1200000000000001
[0.14285714 0.14285714] -0.1428571428571428
[0.16 0.12] -0.1200000000000001
[0.125 0.125] 2.220446049250313e-16
[0.16666667 0.16666667] -0.5000000000000002
[0.12389381 0.14159292] -0.18584070796460184
[0.14159292 0.12389381] -0.20353982300884943
[0.15384615 0.1025641 ] -0.1794871794871793
[0.12413793 0.11034483] -0.062068

In [26]:
# 3 support vectors

three_sv_pos = []
for i in range(len(positive_set)):
    for j in range(i + 1, len(positive_set)):
        for neg_pt in negative_set:
            three_sv_pos.append((positive_set[i], positive_set[j], neg_pt))

three_sv_neg = []
for i in range(len(negative_set)):
    for j in range(i + 1, len(negative_set)):
        for pos_pt in positive_set:
            three_sv_neg.append((negative_set[i], negative_set[j], pos_pt))

three_sv_pos = np.array(three_sv_pos)
three_sv_neg = np.array(three_sv_neg)
print(three_sv_neg)

[[[-1. -2. -1.]
  [-2. -4. -1.]
  [ 3.  2.  1.]]

 [[-1. -2. -1.]
  [-2. -4. -1.]
  [ 6.  2.  1.]]

 [[-1. -2. -1.]
  [-2. -4. -1.]
  [ 3.  6.  1.]]

 [[-1. -2. -1.]
  [-2. -4. -1.]
  [ 4.  4.  1.]]

 [[-1. -2. -1.]
  [-2. -4. -1.]
  [ 5.  4.  1.]]

 [[-1. -2. -1.]
  [-3. -3. -1.]
  [ 3.  2.  1.]]

 [[-1. -2. -1.]
  [-3. -3. -1.]
  [ 6.  2.  1.]]

 [[-1. -2. -1.]
  [-3. -3. -1.]
  [ 3.  6.  1.]]

 [[-1. -2. -1.]
  [-3. -3. -1.]
  [ 4.  4.  1.]]

 [[-1. -2. -1.]
  [-3. -3. -1.]
  [ 5.  4.  1.]]

 [[-1. -2. -1.]
  [-4. -2. -1.]
  [ 3.  2.  1.]]

 [[-1. -2. -1.]
  [-4. -2. -1.]
  [ 6.  2.  1.]]

 [[-1. -2. -1.]
  [-4. -2. -1.]
  [ 3.  6.  1.]]

 [[-1. -2. -1.]
  [-4. -2. -1.]
  [ 4.  4.  1.]]

 [[-1. -2. -1.]
  [-4. -2. -1.]
  [ 5.  4.  1.]]

 [[-1. -2. -1.]
  [-4. -4. -1.]
  [ 3.  2.  1.]]

 [[-1. -2. -1.]
  [-4. -4. -1.]
  [ 6.  2.  1.]]

 [[-1. -2. -1.]
  [-4. -4. -1.]
  [ 3.  6.  1.]]

 [[-1. -2. -1.]
  [-4. -4. -1.]
  [ 4.  4.  1.]]

 [[-1. -2. -1.]
  [-4. -4. -1.]
  [ 5.  4.  1.]]



In [27]:
# Compute w for each triplet of support vectors

for triplet in three_sv_pos:
    two_pts = (triplet[0][:-1], triplet[1][:-1])
    one_pt = triplet[2][:-1]
    midpt = (two_pts[0] + two_pts[1]) / 2     # make midpt a numpy array
    dist = midpt - one_pt
    dir_w = dist / np.linalg.norm(dist)

    gamma = np.linalg.norm(dist) / 2          # margin = half distance
    this_w = dir_w * (1 / gamma)              # same scaling fix

    # If one_pt is the negative SV:
    b = -1 - this_w @ one_pt                  # for negative-class SV
    # If one_pt is positive:
    # b = 1 - this_w @ one_pt

    print(this_w,b)
    w_b.append((this_w,b))

for triplet in three_sv_neg:
    two_pts = (triplet[0][:-1], triplet[1][:-1])
    one_pt = triplet[2][:-1]
    midpt = (two_pts[0] + two_pts[1]) / 2     # make midpt a numpy array
    dist = midpt - one_pt
    dir_w = dist / np.linalg.norm(dist)
    
    gamma = np.linalg.norm(dist) / 2          # margin = half distance
    this_w = dir_w * (1 / gamma)              # same scaling fix
    
    # If one_pt is the negative SV:
    b = -1 - this_w @ one_pt                  # for negative-class SV
    # If one_pt is positive:
    # b = 1 - this_w @ one_pt
    print(this_w,b)
    w_b.append((this_w,b))
    

[0.23783784 0.17297297] -0.4162162162162163
[0.16613419 0.15335463] -0.054313099041533475
[0.18461538 0.12307692] -0.07692307692307687
[0.19263456 0.09065156] -0.04815864022662886
[0.15704388 0.1108545 ] 0.07159353348729791
[0.15384615 0.23076923] -0.3846153846153846
[0.11235955 0.17977528] -0.05617977528089879
[0.14117647 0.16470588] -0.08235294117647063
[0.16470588 0.14117647] -0.05882352941176472
[0.12389381 0.14159292] 0.06194690265486713
[0.19889503 0.22099448] -0.3591160220994474
[0.13880126 0.17665615] -0.015772870662460803
[0.16613419 0.15335463] -0.04153354632587847
[0.18461538 0.12307692] -0.01538461538461533
[0.14251781 0.13301663] 0.10213776722090229
[0.2 0.2] -0.4
[0.14117647 0.16470588] -0.05882352941176472
[0.16470588 0.14117647] -0.08235294117647052
[0.17977528 0.11235955] -0.05617977528089879
[0.14159292 0.12389381] 0.06194690265486713
[0.16603774 0.18113208] -0.4716981132075472
[0.12235294 0.15058824] -0.15294117647058814
[0.14251781 0.13301663] -0.17339667458432317
[

In [28]:
# Verify decision boundary is valid

verified_w_b = []
for w, b in w_b:
    is_valid = True
    for pt in training_data:
        x = pt[:-1]
        y = pt[-1]
        prediction = w @ x + b
        score = y * prediction
        if score < 1:
            is_valid = False
            break
    if is_valid:
        verified_w_b.append((w, b))
        print(w,b)

print(verified_w_b)


[]


In [29]:
# Find w, b with largest margin
largest_margin = 0
for w,b in verified_w_b:
    this_margin = compute_margin(training_data, w, b)
    print(this_margin)
    if this_margin > largest_margin:
        largest_margin = this_margin
        final_w, final_b = w, b

print(final_w, final_b)


NameError: name 'final_w' is not defined

In [ ]:
# # 1. Define the parameters (learned from a classification model)
# w1 = 2.0  # Weight for feature x1
# w2 = -1.5 # Weight for feature x2
# b = -3.0  # Bias

# # The decision boundary equation is: 2.0*x1 - 1.5*x2 - 3.0 = 0

# # 2. Define the x1 (horizontal axis) range
# x1_min, x1_max = -1, 5
# x1 = np.linspace(x1_min, x1_max)

# # 3. Calculate the corresponding x2 (vertical axis) values
# # Rearrange: x2 = (-w1*x1 - b) / w2
# x2 = (-w1 * x1 - b) / w2

# # 4. Plot the line
# plt.plot(x1, x2, color='red')

# plt.grid(True)
# plt.show()

In [ ]:
plot_data_and_boundary(training_data, final_w, final_b)

In [ ]:
for w,b in verified_w_b:
    plot_data_and_boundary(training_data, w, b)