In [457]:
import sys
sys.path.append('..')
from scripts.utils import load_data
from pprint import pprint

X5, Y5 = load_data('../data/data_5.txt')
X6, Y6 = load_data('../data/data_6.txt')

print(X5,Y5,X6,Y6,sep='\n\n')

[[ 0.]
 [ 1.]
 [ 2.]
 [ 7.]
 [ 8.]
 [ 9.]
 [12.]
 [14.]
 [15.]]

[]

[[ 1.  0.]
 [ 7.  4.]
 [ 9.  6.]
 [ 2.  1.]
 [ 4.  8.]
 [ 0.  3.]
 [13.  5.]
 [ 6.  8.]
 [ 7.  3.]
 [ 3.  6.]
 [ 2.  1.]
 [ 8.  3.]
 [10.  2.]
 [ 3.  5.]
 [ 5.  1.]
 [ 1.  9.]
 [10.  3.]
 [ 4.  1.]
 [ 6.  6.]
 [ 2.  2.]]

[]


In [458]:
import numpy as np
from scipy.spatial import distance
import random

In [459]:
def randomize(X, K):
    # Fisher-Yates shuffle
    X_indices = np.arange(len(X))
    for i in range(len(X_indices) - 1, 0, -1):
        j = random.randint(0, i) 
        X_indices[i], X_indices[j] = X_indices[j], X_indices[i]
    return X_indices[:K]

def recalculate_clusters(X, mu):
    clusters = [[] for _ in mu]

    print(f'{[mu[idx] for idx,_ in enumerate(clusters)]} cluster back to mu verification')
    print(f'{clusters} empty clusters')
    print('\n')

    for point in X:
        # Get distance between point and each cluster
        distances = []
        for cluster in mu:
            distances.append(distance.euclidean(point, cluster))
        # Select closest cluster

        print(f'{mu.T} mu')
        print(f'{distances} point to cluster distances')

        closest_cluster_idx = np.argmin(distances) # Potential flaw for same distances
        clusters[closest_cluster_idx].append(point)

        print(f'{distances[closest_cluster_idx]} closest cluster distance')
        print(f'{clusters[closest_cluster_idx]} cluster #{closest_cluster_idx} after append')
        print(f'{mu[closest_cluster_idx]} cluster position')
        print(f'{point} point')
        print('\n\n')

    for idx, cluster in enumerate(clusters):
        cluster = np.array(cluster)
        print(f'{cluster} cluster #{idx}')

    new_mu = []
    for idx, cluster in enumerate(clusters):
        if cluster:
            new_mu.append(np.mean(clusters[idx], axis=0))
        else:
            new_mu.append(mu[idx])

    new_mu = np.array(new_mu)

    print(f'{mu} old mu')
    print(f'{new_mu} new mu')

    return new_mu

def KMeans(X: np.ndarray, K, mu: np.ndarray):
    mu = list(mu)
    # Randomize starting points for K amount of Clusters
    if not mu:
        X_size = len(X)
        random_starting_points = randomize(X, K)
        mu = X[random_starting_points]

    new_mu = mu
    converged = False
    while not converged:
        mu = new_mu
        new_mu = recalculate_clusters(X, mu)
        converged = np.allclose(new_mu, mu)
    
    print(f'{mu} final mu')


   





In [460]:
# print(X5)
# randomize(X5)
KMeans(X5, 3, [])

[array([8.]), array([15.]), array([1.])] cluster back to mu verification
[[], [], []] empty clusters


[[ 8. 15.  1.]] mu
[8.0, 15.0, 1.0] point to cluster distances
1.0 closest cluster distance
[array([0.])] cluster #2 after append
[1.] cluster position
[0.] point



[[ 8. 15.  1.]] mu
[7.0, 14.0, 0.0] point to cluster distances
0.0 closest cluster distance
[array([0.]), array([1.])] cluster #2 after append
[1.] cluster position
[1.] point



[[ 8. 15.  1.]] mu
[6.0, 13.0, 1.0] point to cluster distances
1.0 closest cluster distance
[array([0.]), array([1.]), array([2.])] cluster #2 after append
[1.] cluster position
[2.] point



[[ 8. 15.  1.]] mu
[1.0, 8.0, 6.0] point to cluster distances
1.0 closest cluster distance
[array([7.])] cluster #0 after append
[8.] cluster position
[7.] point



[[ 8. 15.  1.]] mu
[0.0, 7.0, 7.0] point to cluster distances
0.0 closest cluster distance
[array([7.]), array([8.])] cluster #0 after append
[8.] cluster position
[8.] point



[[ 8. 15.  1.]] m